
model_dir: models
n_models: 3

n_mlp_layers: 1
n_prop_steps: 2  
batch_size: 40
mlp_dropout: 0.5
feat_dropout: 0.0 
attn_dropout: 0.0
n_hidden: 512
residual: True
attn_heads: 1
share_weight: True

alphas:
  bp: 0.3
  mf: 0.4
  cc: 0.9
